String ngrok = "https://af52dfeba474.ngrok.io/";
String userNameText;
String userContactText;
String userEmailText;
String userGenderText;
String userAgeText;
String userDisabilityText;
List doctorList;
String docId;
String docName;
String depName;
Map newSlotMap;
List slots;
