String ngrok = "https://db43ccfc7ea8.ngrok.io/";
String userNameText;
String userContactText;
String userEmailText;
String userGenderText;
String userAgeText;
String userDisabilityText;
List doctorList;
String docId;
String docName;
String depName;
