String ngrok = "https://e8f8bf7a3b19.ngrok.io/";
String userNameText;
String userContactText;
String userEmailText;
String userGenderText;
String userAgeText;
String userDisabilityText;
List doctorList;
String docId;
String docName;
String depName;
